from datetime import timedelta

FRESH_LOGIN_WINDOW_SECONDS = 5 * 60
FRESH_LOGIN_WINDOW_TD = timedelta(seconds = FRESH_LOGIN_WINDOW_SECONDS)

CONCURRENT_REFRESH_GRACE_SECONDS = 5
CONCURRENT_REFRESH_GRACE_TD = timedelta(seconds = CONCURRENT_REFRESH_GRACE_SECONDS)