ACCESS_TOKEN_LIFETIME_MINUTES = 15
# 15 minutes * (60 sec / 1 min)
ACCESS_TOKEN_LIFETIME_SECONDS = ACCESS_TOKEN_LIFETIME_MINUTES * 60

REFRESH_TOKEN_LIFETIME_DAYS = 7
# 7 days * (24 hrs / day) * (60 min / 1 hr) * # (60 sec / min)
REFRESH_TOKEN_LIFETIME_SECONDS = REFRESH_TOKEN_LIFETIME_DAYS * 24 * 60 * 60