"""add refresh_token_id to session_tokens table and rename token_hash

Revision ID: 90373757b20e
Revises: 33bdf3ea00db
Create Date: 2026-08-11 11:35:11.119303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90373757b20e'
down_revision: Union[str, Sequence[str], None] = '33bdf3ea00db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_tokens', sa.Column('refresh_token_hash', sa.String(), nullable=False))
    op.add_column('session_tokens', sa.Column('refresh_token_id', sa.UUID(), nullable=False))
    op.drop_column('session_tokens', 'token_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'session_tokens', 
        sa.Column('token_hash', sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.drop_column('session_tokens', 'refresh_token_id')
    op.drop_column('session_tokens', 'refresh_token_hash')
    # ### end Alembic commands ###
