"""add email verification fields to users table

Revision ID: afc8abad5816
Revises: b1a0392ba890
Create Date: 2026-07-17 17:24:41.234589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'afc8abad5816'
down_revision: Union[str, Sequence[str], None] = 'b1a0392ba890'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        'users',
        sa.Column(
            'is_verified',
            sa.Boolean(),
            server_default=sa.text('false'),
            nullable=False
        )
    )
    op.add_column(
        'users',
        sa.Column(
            'verified_at',
            sa.DateTime(timezone=True),
            nullable=True
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verified_at')
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
