"""create user_tea_profile_notes table

Revision ID: b1a0392ba890
Revises: 176db9e8efd2
Create Date: 2026-07-07 18:39:14.945652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b1a0392ba890'
down_revision: Union[str, Sequence[str], None] = '176db9e8efd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_tea_profile_notes',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('tea_profile_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('alternative_names', sa.Text(), nullable=False),
        sa.Column('cultivars', sa.Text(), nullable=False),
        sa.Column('processing', sa.Text(), nullable=False),
        sa.Column('oxidation_level', sa.Text(), nullable=False),
        sa.Column('cultural_significance', sa.Text(), nullable=False),
        sa.Column('cultural_significance_source', sa.Text(), nullable=False),
        sa.Column('subregions', sa.Text(), nullable=False),
        sa.Column('liquor_appearance', sa.Text(), nullable=False),
        sa.Column('liquor_aroma', sa.Text(), nullable=False),
        sa.Column('liquor_taste', sa.Text(), nullable=False),
        sa.Column('liquor_body_mouthfeel', sa.Text(), nullable=False),
        sa.Column('body_effect', sa.Text(), nullable=False),
        sa.Column('dry_leaf_appearance', sa.Text(), nullable=False),
        sa.Column('dry_leaf_aroma', sa.Text(), nullable=False),
        sa.Column('wet_leaf_appearance', sa.Text(), nullable=False),
        sa.Column('wet_leaf_aroma', sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(['tea_profile_id'], ['tea_profiles.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('user_tea_profile_notes')
