"""Add unique constraint on tea_profiles.name

Revision ID: ed74601e8937
Revises: 
Create Date: 2025-11-17 17:55:35.713512

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ed74601e8937'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('tea_profiles')
    op.create_unique_constraint(
        "tea_profiles_name_key",  # constraint name
        "tea_profiles",           # table name
        ["name"]                  # columns
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('tea_profiles',
    # sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    # sa.Column('alternative_names', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, 
    #   nullable=True),
    # sa.Column('tea_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    # sa.Column('cultivars', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, 
    #   nullable=False),
    # sa.Column('processing', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.Column('oxidation_level', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.Column('cultural_significance', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.Column('cultural_significance_source', sa.VARCHAR(), autoincrement=False, 
    #   nullable=True),
    # sa.Column('country_of_origin', sa.VARCHAR(), autoincrement=False, nullable=False),
    # sa.Column('subregions', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, 
    #   nullable=True),
    # sa.Column('avg_price_per_oz_usd', sa.NUMERIC(precision=7, scale=2), 
    #   autoincrement=False, nullable=True),
    # sa.Column('liquor_appearance', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, 
    #   nullable=False),
    # sa.Column('liquor_aroma', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, 
    #   nullable=False),
    # sa.Column('liquor_taste', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, 
    #   nullable=False),
    # sa.Column('liquor_body_mouthfeel', postgresql.ARRAY(sa.VARCHAR()), 
    #   autoincrement=False, nullable=True),
    # sa.Column('body_effect', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, 
    #   nullable=True),
    # sa.Column('dry_leaf_appearance', postgresql.ARRAY(sa.VARCHAR()), 
    #   autoincrement=False, nullable=True),
    # sa.Column('dry_leaf_aroma', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, 
    #   nullable=True),
    # sa.Column('wet_leaf_appearance', postgresql.ARRAY(sa.VARCHAR()), 
    #   autoincrement=False, nullable=True),
    # sa.Column('wet_leaf_aroma', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, 
    #   nullable=True),
    # sa.PrimaryKeyConstraint('id', name=op.f('tea_profiles_pkey'))
    # )
    op.drop_constraint(
        "tea_profiles_name_key",
        "tea_profiles",
        type_="unique"
    )
    # ### end Alembic commands ###
